const FALLBACK_API_URL = "http://localhost:8080/v1";

export const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL || FALLBACK_API_URL;

// chwilowo trzeba kopiowac ze swaggera rozwiąze sie to jak zrobimy auth u nas
export const DEV_JWT_TOKEN =
  "eyJhbGciOiJFUzI1NiIsImtpZCI6IjFhNWJiNjQ5LTg5NzktNGU2YS05OWMzLTVjZTkyMGI2NTAzOSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL25qb3BhbGt3enBvYXFrY3dzZWl0LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyMzU5MTdjMy1kZTYxLTQwOGMtOTM2Ny1jOTViM2I0MjhmYWEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgwMjM1Njc0LCJpYXQiOjE3ODAyMzIwNzQsImVtYWlsIjoiMjcyODkwQHN0dWRlbnQucHdyLmVkdS5wbCIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzgwMjMyMDc0fV0sInNlc3Npb25faWQiOiI1MDMwYTdlNy04YmQ1LTQ5MjgtOTZhNy05NmU4YTg1YzI0Y2EiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.0h_frab3jrJy2IajAn-ewcRoZIae7TBSo2hVsETgDJMtJQ4VekFB4o9nVqabQSOH93QMhdAsoKq58k549M-64w";
